# data_exploration.ipynb
test "enviroment"

In [97]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go 
import numpy as np

Loading data from csv:s

# Cleaning, searching and shaping data

In [98]:
# Load the datasets
Games_score = pd.read_csv("Resources/games-score.csv")
Consoles_sales = pd.read_csv("Resources/best-selling game consoles.csv")
Game_sales = pd.read_csv("Resources/video games sales.csv")

# Quick look at the data
print("Games_score shape:", Games_score.shape)
print("Consoles_sales shape:", Consoles_sales.shape)
print("Game_sales shape:", Game_sales.shape)

Games_score shape: (20022, 8)
Consoles_sales shape: (51, 7)
Game_sales shape: (16598, 11)

In [99]:
Games_score.head(10)

,id,metascore,platform,release_date,sort_no,summary,title,user_score
0,543718,91,PC,"August 18, 2020",301,"From light planes to wide-body jets, fly highl...",Microsoft Flight Simulator,7.1
1,555108,91,PC,"December 8, 2022",302,"Take up your sword, channel your magic or boar...",Chained Echoes,8.7
2,106820,91,PlayStation 2,"November 7, 2005",303,"Strap on your Guitar Hero SG controller, plug-...",Guitar Hero,8.5
3,110775,91,PC,"November 13, 2008",304,"Players last visited Northrend in ""Warcraft II...",World of Warcraft: Wrath of the Lich King,7.7
4,142864,91,Wii,"October 26, 2010",305,Rock Band returns with the third iteration of ...,Rock Band 3,6.8
5,114951,91,Wii,"August 24, 2009",306,Metroid Prime 3: Corruption set a new standard...,Metroid Prime Trilogy,9
6,397035,91,PC,"May 23, 2016",307,Overwatch is a highly stylized team-based shoo...,Overwatch,6.4
7,102812,91,PC,"June 24, 2003",308,Cutting-edge technology brings you the most ac...,F1 Challenge '99-'02,7.7
8,161540,91,GameCube,"October 23, 2002",309,Drop into the ultimate challenge. In the next...,Tony Hawk's Pro Skater 4,8.2
9,100705,91,PlayStation 2,"October 23, 2000",310,EA Sports steps up to the challenge of Sega's ...,Madden NFL 2001,7.5

In [100]:
Consoles_sales.head(10)

,Console Name,Type,Company,Released Year,Discontinuation Year,Units sold (million),Remarks
0,PlayStation 2,Home,Sony,2000,2013,155.00,Final sales are greater than 155 million
1,Nintendo DS,Handheld,Nintendo,2004,2013,154.02,NaN
2,Nintendo Switch,Hybrid,Nintendo,2017,0,122.55,NaN
3,Game Boy,Handheld,Nintendo,1989,2003,64.42,The Game Boy (1989) and the Game Boy Color (19...
4,Game Boy Color,Handheld,Nintendo,1998,2003,44.06,NaN
5,PlayStation 4,Home,Sony,2013,0,117.20,NaN
6,PlayStation,Home,Sony,1994,2006,102.49,NaN
7,Wii,Home,Nintendo,2006,2013,101.63,NaN
8,PlayStation 3,Home,Sony,2006,2017,87.40,Final sales are greater than 87.4 million
9,Xbox 360,Home,Microsoft,2005,2016,84.00,Final sales are greater than 84 million

In [101]:
Game_sales.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

Testing, analyzing

In [102]:
# Clean Games_score
Games_score["user_score"] = pd.to_numeric(Games_score["user_score"], errors="coerce") * 10  
Games_score["release_date"] = pd.to_datetime(Games_score["release_date"])

# Clean Game_sales
Game_sales["Year"] = Game_sales["Year"].fillna(Game_sales["Year"].median())
Game_sales["Publisher"] = Game_sales["Publisher"].fillna("Unknown")

# Check for missing values
print("Missing values in Games_score:")
print(Games_score[["user_score", "metascore"]].isna().sum())
print("\nMissing values in Game_sales:")
print(Game_sales[["Name", "Platform", "Global_Sales"]].isna().sum())

Missing values in Games_score:
user_score    1382
metascore        0
dtype: int64

Missing values in Game_sales:
Name            0
Platform        0
Global_Sales    0
dtype: int64

In [103]:
# Normalize platform names for merging
platform_normalization = {
    "PS": "PlayStation", "PS2": "PlayStation 2", "PS3": "PlayStation 3", "PS4": "PlayStation 4",
    "XB": "Xbox", "X360": "Xbox 360", "XOne": "Xbox One",
    "NES": "NES", "SNES": "SNES", "Wii": "Wii", "Switch": "Nintendo Switch",
    "DC": "Dreamcast", "Wii U": "Wii U", "WiiU": "Wii U",
    "GC": "GameCube", "3DS": "Nintendo 3DS",
    "GB": "Game Boy", "GBA": "Game Boy Advance", "DS": "Nintendo DS", "N64": "Nintendo 64",
    "PSP": "PlayStation Portable", "GBC": "Game Boy Color", "DSI": "Nintendo DSi",
    "GEN": "Sega Genesis", "SAT": "Sega Saturn", "S32X": "Sega 32X", "SCD": "Sega CD",
    "PC": "PC"
}
Game_sales["Platform_normalized"] = Game_sales["Platform"].map(platform_normalization)
Games_score["platform_normalized"] = Games_score["platform"].map(lambda x: platform_normalization.get(x, x))

# Merge the datasets
merged_games = pd.merge(Game_sales, Games_score, left_on=["Name", "Platform_normalized"], 
                        right_on=["title", "platform_normalized"], how="left")

# Check the merge
print("Merged games shape:", merged_games.shape)
print("Missing metascore after merge:", merged_games["metascore"].isna().sum())
print("Missing user_score after merge:", merged_games["user_score"].isna().sum())

# Check Wii U games specifically
wiiu_games = merged_games[merged_games["Platform"].str.contains("WiiU", na=False)]
print("Number of Wii U games:", len(wiiu_games))
print("Wii U games with metascore:", wiiu_games["metascore"].notna().sum())
print("Wii U games with user_score:", wiiu_games["user_score"].notna().sum())
print("Sample of Wii U games:")
print(wiiu_games[["title", "platform", "metascore", "user_score"]].head())

Merged games shape: (16598, 21)
Missing metascore after merge: 9777
Missing user_score after merge: 10199
Number of Wii U games: 143
Wii U games with metascore: 60
Wii U games with user_score: 60
Sample of Wii U games:
                       title platform  metascore  user_score
108             Mario Kart 8    Wii U       88.0        88.0
183  New Super Mario Bros. U    Wii U       84.0        80.0
203                      NaN      NaN        NaN         NaN
235                 Splatoon    Wii U       81.0        87.0
246            Nintendo Land    Wii U       77.0        79.0

In [104]:
# Map platforms to manufacturers
manufacturer_map = {
    "PS": "Sony", "PS2": "Sony", "PS3": "Sony", "PS4": "Sony", "PSP": "Sony",
    "XB": "Microsoft", "X360": "Microsoft", "XOne": "Microsoft",
    "NES": "Nintendo", "SNES": "Nintendo", "Wii": "Nintendo", "Switch": "Nintendo",
    "DC": "Sega", "Wii U": "Nintendo", "GC": "Nintendo", "3DS": "Nintendo",
    "GB": "Nintendo", "GBA": "Nintendo", "DS": "Nintendo", "N64": "Nintendo",
    "GBC": "Nintendo", "DSI": "Nintendo",
    "GEN": "Sega", "SAT": "Sega", "S32X": "Sega", "SCD": "Sega",
    "PC": "Others"
}
merged_games["manufacturer"] = merged_games["Platform"].map(manufacturer_map).fillna("Others")
merged_games = merged_games.drop_duplicates(subset=["Name", "Platform"])
merged_games["avg_score"] = merged_games[["metascore", "user_score"]].mean(axis=1)

# Check the distribution of manufacturers
print("Number of games per manufacturer:")
print(merged_games["manufacturer"].value_counts())

Number of games per manufacturer:
manufacturer
Sony         6233
Nintendo     6128
Microsoft    2301
Others       1673
Sega          258
Name: count, dtype: int64

In [105]:
# Check platform differences
print("Unique platforms in Game_sales:", Game_sales["Platform"].unique())
print("Unique platforms in Games_score:", Games_score["platform"].unique())
#print("Unique platforms in Others:", others_games["Platform"].unique())

# Test matching for Wii U games
wiiu_games_sales = Game_sales[Game_sales["Platform"].str.contains("WiiU", na=False)]
wiiu_games_score = Games_score[Games_score["platform"].str.contains("Wii U", na=False)]
print("Wii U in Game_sales:")
print(wiiu_games_sales[["Name", "Platform", "Platform_normalized"]].head())
print("Wii U in Games_score:")
print(wiiu_games_score[["title", "platform", "platform_normalized"]].head())

# Test matching for PC games
pc_games_sales = Game_sales[Game_sales["Platform"] == "PC"]
pc_games_score = Games_score[Games_score["platform"] == "PC"]
print("PC in Game_sales:")
print(pc_games_sales[["Name", "Platform", "Platform_normalized"]].head())
print("PC in Games_score:")
print(pc_games_score[["title", "platform", "platform_normalized"]].head())

Unique platforms in Game_sales: ['Wii' 'NES' 'GB' 'DS' 'X360' 'PS3' 'PS2' 'SNES' 'GBA' '3DS' 'PS4' 'N64'
 'PS' 'XB' 'PC' '2600' 'PSP' 'XOne' 'GC' 'WiiU' 'GEN' 'DC' 'PSV' 'SAT'
 'SCD' 'WS' 'NG' 'TG16' '3DO' 'GG' 'PCFX']
Unique platforms in Games_score: ['PC' 'PlayStation 2' 'Wii' 'GameCube' 'Wii U' 'Xbox One' 'PlayStation 3'
 'Nintendo 64' 'PlayStation' 'Switch' 'Xbox' 'PSP' 'PlayStation 4'
 'Game Boy Advance' 'Xbox 360' 'PlayStation 5' '3DS' 'Dreamcast'
 'Xbox Series X' 'DS' 'PlayStation Vita' 'Stadia']
Wii U in Game_sales:
                                    Name Platform Platform_normalized
108                         Mario Kart 8     WiiU               Wii U
183              New Super Mario Bros. U     WiiU               Wii U
203  Super Smash Bros. for Wii U and 3DS     WiiU               Wii U
235                             Splatoon     WiiU               Wii U
246                        Nintendo Land     WiiU               Wii U
Wii U in Games_score:
                                       title platform platform_normalized
11                               Bayonetta 2    Wii U               Wii U
125  The Legend of Zelda: Breath of the Wild    Wii U               Wii U
222                              Axiom Verge    Wii U               Wii U
406   The Legend of Zelda: The Wind Waker HD    Wii U               Wii U
432                  Mario Kart 8 DLC Pack 2    Wii U               Wii U
PC in Game_sales:
                               Name Platform Platform_normalized
83                       The Sims 3       PC                  PC
137               World of Warcraft       PC                  PC
181                      Diablo III       PC                  PC
194      Microsoft Flight Simulator       PC                  PC
217  StarCraft II: Wings of Liberty       PC                  PC
PC in Games_score:
                                       title platform platform_normalized
0                 Microsoft Flight Simulator       PC                  PC
1                             Chained Echoes       PC                  PC
3  World of Warcraft: Wrath of the Lich King       PC                  PC
6                                  Overwatch       PC                  PC
7                       F1 Challenge '99-'02       PC                  PC

In [106]:
# Filter for "Others" and check scores
others_games = merged_games[merged_games["manufacturer"] == "Others"]
print("Number of games in Others:", len(others_games))
print("Others games with metascore:", others_games["metascore"].notna().sum())
print("Others games with user_score:", others_games["user_score"].notna().sum())
print("Sample of Others games:")
print(others_games[["Name", "Platform", "metascore", "user_score", "avg_score"]].head(20))

Number of games in Others: 1673
Others games with metascore: 672
Others games with user_score: 672
Sample of Others games:
                                       Name Platform  metascore  user_score  \
83                               The Sims 3       PC       86.0        78.0
89                                  Pac-Man     2600        NaN         NaN
108                            Mario Kart 8     WiiU       88.0        88.0
137                       World of Warcraft       PC       93.0        74.0
181                              Diablo III       PC       88.0        42.0
183                 New Super Mario Bros. U     WiiU       84.0        80.0
194              Microsoft Flight Simulator       PC       91.0        71.0
203     Super Smash Bros. for Wii U and 3DS     WiiU        NaN         NaN
217          StarCraft II: Wings of Liberty       PC        NaN         NaN
235                                Splatoon     WiiU       81.0        87.0
239                                Pitfall!     2600        NaN         NaN
246                           Nintendo Land     WiiU       77.0        79.0
258                               Asteroids     2600        NaN         NaN
261                    Super Mario 3D World     WiiU       93.0        89.0
267          Warcraft II: Tides of Darkness       PC        NaN         NaN
281                               Half-Life       PC       96.0        91.0
288  World of Warcraft: The Burning Crusade       PC       91.0        60.0
310             The Elder Scrolls V: Skyrim       PC       94.0        84.0
328                     The Sims: Unleashed       PC       79.0        77.0
353                  Doom II: Hell on Earth       PC        NaN         NaN

     avg_score
83        82.0
89         NaN
108       88.0
137       83.5
181       65.0
183       82.0
194       81.0
203        NaN
217        NaN
235       84.0
239        NaN
246       78.0
258        NaN
261       91.0
267        NaN
281       93.5
288       75.5
310       89.0
328       78.0
353        NaN

In [107]:
# Map consoles to companies
console_manufacturer_map = {
    "PlayStation": "Sony", "PlayStation 2": "Sony", "PlayStation 3": "Sony", "PlayStation 4": "Sony",
    "PlayStation 5": "Sony","Playstation Vita": "Sony",  
    "PlayStation Portable": "Sony",
    "Xbox": "Microsoft", "Xbox 360": "Microsoft", "Xbox One": "Microsoft",
    "Xbox Series X/S": "Microsoft",  
    "Nintendo Entertainment System": "Nintendo", "Super Nintendo": "Nintendo", "Nintendo 64": "Nintendo",
    "GameCube": "Nintendo", "Wii": "Nintendo", "Wii U": "Nintendo", "Nintendo Switch": "Nintendo",
    "Game Boy": "Nintendo", "Game Boy Advance": "Nintendo", "Nintendo DS": "Nintendo",
    "Game Boy Color": "Nintendo", "Nintendo DSi": "Nintendo",
    "Nintendo 3DS": "Nintendo","PlayStation Vita": "Sony","Game & Watch": "Nintendo", 
    "NES/Famicom": "Nintendo", "SNES/Super Famicom": "Nintendo", "Famicom": "Nintendo", 
    "Sega Genesis": "Sega", "Sega Mega Drive": "Sega", "Sega Saturn": "Sega", "Sega Dreamcast": "Sega",
    "Sega Master System": "Sega", "Sega Game Gear": "Sega", "Sega CD": "Sega", "Sega 32X": "Sega"
}
Consoles_sales["Company"] = Consoles_sales["Console Name"].map(console_manufacturer_map).fillna("Others")

# Check consoles in Others
others_consoles = Consoles_sales[Consoles_sales["Company"] == "Others"]
print("Consoles in Others:")
print(others_consoles[["Console Name", "Company"]])

Consoles in Others:
                         Console Name Company
18            Sega Genesis/Mega Drive  Others
20                         Atari 2600  Others
28            PC Engine/TurboGrafx-16  Others
30                          Dreamcast  Others
31  Master System(Brazilian variants)  Others
32                   Dendy(Famiclone)  Others
33          Super NES Classic Edition  Others
34                Famicom Disk System  Others
35                NES Classic Edition  Others
36                         WonderSwan  Others
37                          Sega Pico  Others
38                      Color TV-Game  Others
39                      Intellivision  Others
40     Mega Drive(Brazilian variants)  Others
41                             N-Gage  Others
43                       ColecoVision  Others
44                   Magnavox Odyssey  Others
45                   PC Engine CD-ROM  Others
46                         Atari 7800  Others
47                         Atari Lynx  Others
48                       Philips CD-i  Others
49                            Telstar  Others
50                         Atari 5200  Others

Creating and merging files in platform/platform creator

In [108]:
summary = merged_games.groupby("Platform_normalized").agg({
    "Name": "count",  # Räknar antal spel
    "Global_Sales": "sum"  # Summerar global försäljning
}).rename(columns={"Name": "Antal Spel", "Global_Sales": "Total Försäljning på spel i (Miljoner)"})
summary

                      Antal Spel  Total Försäljning på spel i (Miljoner)
Platform_normalized
Dreamcast                     52                                   15.97
Game Boy                      98                                  255.45
Game Boy Advance             822                                  318.50
GameCube                     556                                  199.36
NES                           98                                  251.07
Nintendo 3DS                 509                                  247.46
Nintendo 64                  319                                  218.88
Nintendo DS                 2163                                  822.49
PC                           959                                  258.74
PlayStation                 1196                                  730.66
PlayStation 2               2161                                 1255.64
PlayStation 3               1327                                  957.35
PlayStation 4                336                                  278.10
PlayStation Portable        1213                                  296.28
SNES                         239                                  200.05
Sega CD                        6                                    1.87
Sega Genesis                  27                                   28.36
Sega Saturn                  173                                   33.59
Wii                         1324                                  926.69
Wii U                        143                                   81.86
Xbox                         824                                  258.26
Xbox 360                    1264                                  978.67
Xbox One                     213                                  141.06

In [109]:
merged_games["Global_Sales"] = merged_games["Global_Sales"]

merged_games

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,...,metascore,platform,release_date,sort_no,summary,title,user_score,platform_normalized,manufacturer,avg_score
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,...,76.0,Wii,2006-11-19,7798.0,Tennis (1-4 players): Players grab the control...,Wii Sports,81.0,Wii,Nintendo,78.5
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,Nintendo,NaN
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,...,82.0,Wii,2008-04-27,3417.0,Mario Kart Wii comes with the intuitive Wii Wh...,Mario Kart Wii,85.0,Wii,Nintendo,83.5
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,...,80.0,Wii,2009-07-26,4453.0,Wii Sports Resort is a collection of fun sport...,Wii Sports Resort,83.0,Wii,Nintendo,81.5
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,Nintendo,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,Nintendo,NaN
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,Nintendo,NaN
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,Sony,NaN
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,Nintendo,NaN
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,Nintendo,NaN

In [110]:
# Define color schemes for experimentation
manufacturer_colors = {
    "Nintendo": "#1f77b4",  # Blue
    "Sony": "#2ca02c",      # Green
    "Microsoft": "#d62728", # Red
    "Others": "#7f7f7f",    # Gray
    "Sega": "#ff7f0e"       # Orange
}

# Choropleth map color scale (shades of blue)
choropleth_color_scale = "PiYg"

# Filter for Others and try a scatterplot
filtered_games = merged_games[merged_games["manufacturer"] == "Others"]
if filtered_games["metascore"].notna().sum() == 0:
    print("No score data available for Others.")
else:
    fig_scores = px.scatter(filtered_games, x="metascore", y="user_score", hover_data=["Name"], 
                            title="Metascore vs User Score (0-100)",
                            color="manufacturer", color_discrete_map=manufacturer_colors)
    fig_scores.show()

# Top 15 games by avg_score
top_15_scores = filtered_games[filtered_games["avg_score"].notna()].nlargest(15, "avg_score")
fig_top_scores = px.bar(top_15_scores, x="Name", y="avg_score", title="Top 15 Games (Average Score 0-100)",
                        color="manufacturer", color_discrete_map=manufacturer_colors)
fig_top_scores.show()

# Bottom 15 games by avg_score
bottom_15_scores = filtered_games[filtered_games["avg_score"].notna()].nsmallest(15, "avg_score")
fig_bottom_scores = px.bar(bottom_15_scores, x="Name", y="avg_score", title="Bottom 15 Games (Average Score 0-100)",
                           color="manufacturer", color_discrete_map=manufacturer_colors)
fig_bottom_scores.show()

# Shared page visualizations (all consoles)
# Top games (treemap)
top_games_all = merged_games.nlargest(10, "Global_Sales")
fig_top_games_all = px.treemap(top_games_all, path=["manufacturer", "Name"], values="Global_Sales",
                               title="Top 10 Games by Sales (All Consoles)",
                               color="manufacturer", color_discrete_map=manufacturer_colors)
fig_top_games_all.show()

# Console sales (pie chart)
console_sales_by_company = Consoles_sales.groupby("Company")["Units sold (million)"].sum().reset_index()
fig_console_sales_all = px.pie(console_sales_by_company, names="Company", values="Units sold (million)",
                               title="Console Sales by Company (All Consoles)",
                               color="Company", color_discrete_map=manufacturer_colors)
fig_console_sales_all.show()

# Scores (box plot)
fig_scores_all = px.box(merged_games[merged_games["avg_score"].notna()], x="manufacturer", y="avg_score",
                        title="Score Distribution by Manufacturer (All Consoles)",
                        color="manufacturer", color_discrete_map=manufacturer_colors)
fig_scores_all.show()

# Choropleth map for regional sales
# Aggregate regional sales
regional_sales = {
    "Region": ["NA", "EU", "JP"],
    "Sales": [
        merged_games["NA_Sales"].sum(),
        merged_games["EU_Sales"].sum(),
        merged_games["JP_Sales"].sum()
    ]
}
regional_sales_df = pd.DataFrame(regional_sales)

# Map regions to countries (simplified)
region_to_countries = {
    "NA": ["USA", "CAN", "MEX"],
    "EU": ["DEU", "FRA", "ITA", "ESP", "SWE", "DNK", "FIN", "POL", "BEL", "GRC", "ROU", "IRL", "EST", "LTU", 
            "NLD", "CHE", "AUT", "HUN", "SVK", "SVN", "CZE", "HRV", "PRT", "LUX", "MLT", "CYP", "LVA", "BGR",
            "BLR","UKR","ISL","GBR","NOR","ALB","MKD","SRB","BIH","MNE","MLD","MDA"],  
    "JP": ["JPN"]
}

# Create a DataFrame for the choropleth map
choropleth_data = []
for _, row in regional_sales_df.iterrows():
    region = row["Region"]
    sales = row["Sales"]
    for country in region_to_countries[region]:
        choropleth_data.append({"Country": country, "Sales": sales, "Region": region})
choropleth_df = pd.DataFrame(choropleth_data)

# Create the choropleth map
fig_choropleth = px.choropleth(choropleth_df, locations="Country", locationmode="ISO-3",
                               color="Sales", hover_name="Country", hover_data=["Region"],
                               title="Regional Sales (Millions)",
                               color_continuous_scale=choropleth_color_scale)
fig_choropleth.show()

# Mock game search
search_term = "Mario"  # You can change this to test different games
search_results = merged_games[merged_games["Name"].str.contains(search_term, case=False, na=False)]
print(f"Search results for '{search_term}':")
#print(search_results[["Name", "Platform", "Manufacturer", "Global_Sales", "Metascore", "User_score", "Avg score"]].head(10))

Search results for 'Mario':

In [111]:
choropleth_color_scale = "PiYg"
selected_game = ("Pokemon Black/Pokemon White ")  
game_data = merged_games[merged_games["Name"] == selected_game]
regional_sales = {
    "Region": ["NA", "EU", "JP"],
    "Sales": [
        game_data["NA_Sales"].sum(),
        game_data["EU_Sales"].sum(),
        game_data["JP_Sales"].sum()
    ]
}

choropleth_data = []
for _, row in regional_sales_df.iterrows():
    region = row["Region"]
    sales = row["Sales"]
    for country in region_to_countries[region]:
        choropleth_data.append({"Country": country, "Sales": sales, "Region": region})
choropleth_df = pd.DataFrame(choropleth_data)

# Create the choropleth map
fig_choropleth = px.choropleth(choropleth_df, locations="Country", locationmode="ISO-3",
                               color="Sales", hover_name="Country", hover_data=["Region"],
                               title="Regional Sales (Millions)",
                               color_continuous_scale=choropleth_color_scale)
fig_choropleth.show()
#print(game_data)
#print(regional_sales)
print(choropleth_df)
print(choropleth_df.head())

   Country    Sales Region
0      USA  4391.95     NA
1      CAN  4391.95     NA
2      MEX  4391.95     NA
3      DEU  2433.41     EU
4      FRA  2433.41     EU
5      ITA  2433.41     EU
6      ESP  2433.41     EU
7      SWE  2433.41     EU
8      DNK  2433.41     EU
9      FIN  2433.41     EU
10     POL  2433.41     EU
11     BEL  2433.41     EU
12     GRC  2433.41     EU
13     ROU  2433.41     EU
14     IRL  2433.41     EU
15     EST  2433.41     EU
16     LTU  2433.41     EU
17     NLD  2433.41     EU
18     CHE  2433.41     EU
19     AUT  2433.41     EU
20     HUN  2433.41     EU
21     SVK  2433.41     EU
22     SVN  2433.41     EU
23     CZE  2433.41     EU
24     HRV  2433.41     EU
25     PRT  2433.41     EU
26     LUX  2433.41     EU
27     MLT  2433.41     EU
28     CYP  2433.41     EU
29     LVA  2433.41     EU
30     BGR  2433.41     EU
31     BLR  2433.41     EU
32     UKR  2433.41     EU
33     ISL  2433.41     EU
34     GBR  2433.41     EU
35     NOR  2433.41     EU
36     ALB  2433.41     EU
37     MKD  2433.41     EU
38     SRB  2433.41     EU
39     BIH  2433.41     EU
40     MNE  2433.41     EU
41     MLD  2433.41     EU
42     MDA  2433.41     EU
43     JPN  1290.98     JP
  Country    Sales Region
0     USA  4391.95     NA
1     CAN  4391.95     NA
2     MEX  4391.95     NA
3     DEU  2433.41     EU
4     FRA  2433.41     EU

In [112]:
fig_choropleth = px.choropleth(
    choropleth_df, locations="Country", locationmode="ISO-3",
    color="Sales", hover_name="Country", hover_data=["Region"],
    title=f"Regional Sales for {selected_game} (Millions)",
    color_continuous_scale=choropleth_color_scale
)
fig_choropleth.show()
print(f"Selected game: {selected_game}")
print(choropleth_df.head())
print(regional_sales)

Selected game: Pokemon Black/Pokemon White
  Country    Sales Region
0     USA  4391.95     NA
1     CAN  4391.95     NA
2     MEX  4391.95     NA
3     DEU  2433.41     EU
4     FRA  2433.41     EU
{'Region': ['NA', 'EU', 'JP'], 'Sales': [np.float64(0.0), np.float64(0.0), np.float64(0.0)]}

In [113]:

# Filtrera för det valda spelet
selected_game_data = merged_games[merged_games["Name"] == selected_game]

# Kontrollera om det finns data för spelet
if selected_game_data.empty:
    print(f"No data found for the selected game: {selected_game}")
else:
    # Summera försäljningen för det valda spelet
    regional_sales = {
        "Region": ["NA", "EU", "JP"],
        "Sales": [
            selected_game_data["NA_Sales"].sum(),
            selected_game_data["EU_Sales"].sum(),
            selected_game_data["JP_Sales"].sum()
        ]
    }
    regional_sales_df = pd.DataFrame(regional_sales)

    # Map regions to countries (som tidigare)
    choropleth_data = []
    for _, row in regional_sales_df.iterrows():
        region = row["Region"]
        sales = row["Sales"]
        for country in region_to_countries[region]:
            choropleth_data.append({"Country": country, "Sales": sales, "Region": region})
    choropleth_df = pd.DataFrame(choropleth_data)

    # Skapa och visa kartan
    fig_choropleth = px.choropleth(
        choropleth_df, locations="Country", locationmode="ISO-3",
        color="Sales", hover_name="Country", hover_data=["Region"],
        title=f"Regional Sales for {selected_game} (Millions)",
        color_continuous_scale=choropleth_color_scale
    )
    fig_choropleth.show()

No data found for the selected game: Pokemon Black/Pokemon White

In [114]:
# Fixed colour test.
fig = px.colors.sequential.swatches_continuous()
fig.show()
fig = px.colors.diverging.swatches_continuous()
fig.show()

Tar bort dubletter

In [115]:
summary = merged_games.groupby("Platform_normalized").agg({
    "Name": "count",  # Räknar antal spel
    "Global_Sales": "sum"  # Summerar global försäljning
}).rename(columns={"Name": "Number of games", "Global_Sales": "Game Sales (Millions)"})

#summary["Game Sales (Millions)"] = summary["Game Sales (Millions)"].round(1)  # Runda av till en decimal
#summary.index.name = "Plattform"  # Ändra visningsnamnet för index
summary

                      Number of games  Game Sales (Millions)
Platform_normalized
Dreamcast                          52                  15.97
Game Boy                           98                 255.45
Game Boy Advance                  822                 318.50
GameCube                          556                 199.36
NES                                98                 251.07
Nintendo 3DS                      509                 247.46
Nintendo 64                       319                 218.88
Nintendo DS                      2163                 822.49
PC                                959                 258.74
PlayStation                      1196                 730.66
PlayStation 2                    2161                1255.64
PlayStation 3                    1327                 957.35
PlayStation 4                     336                 278.10
PlayStation Portable             1213                 296.28
SNES                              239                 200.05
Sega CD                             6                   1.87
Sega Genesis                       27                  28.36
Sega Saturn                       173                  33.59
Wii                              1324                 926.69
Wii U                             143                  81.86
Xbox                              824                 258.26
Xbox 360                         1264                 978.67
Xbox One                          213                 141.06

In [116]:
merged_games = merged_games.drop_duplicates(subset=["Name", "Platform"])

In [117]:
merged_games["NA_Sales"] = merged_games["NA_Sales"].fillna(0)
merged_games["EU_Sales"] = merged_games["EU_Sales"].fillna(0)
merged_games["JP_Sales"] = merged_games["JP_Sales"].fillna(0)
print(merged_games[["NA_Sales", "EU_Sales", "JP_Sales"]].sum())
print(regional_sales_df)

NA_Sales    4391.95
EU_Sales    2433.41
JP_Sales    1290.98
dtype: float64
  Region    Sales
0     NA  4391.95
1     EU  2433.41
2     JP  1290.98

In [118]:
print(merged_games[["Global_Sales", "metascore", "user_score"]].isna().sum())

Global_Sales        0
metascore        9775
user_score      10197
dtype: int64

In [119]:
#Kontrollera saknade tillverkare
print("Plattformar utan tillverkare:")
print(merged_games[merged_games["manufacturer"].isna()]["Platform"].unique())

Plattformar utan tillverkare:
[]

In [120]:
print(merged_games.head())

   Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  ...  metascore platform  \
0     41.49     29.02      3.77         8.46  ...       76.0      Wii
1     29.08      3.58      6.81         0.77  ...        NaN      NaN
2     15.85     12.88      3.79         3.31  ...       82.0      Wii
3     15.75     11.01      3.28         2.96  ...       80.0      Wii
4     11.27      8.89     10.22         1.00  ...        NaN      NaN

   release_date  sort_no                                            summary  \
0    2006-11-19   7798.0  Tennis (1-4 players): Players grab the control...
1           NaT      NaN                                                NaN
2    2008-04-27   3417.0  Mario Kart Wii comes with the intuitive Wii Wh...
3    2009-07-26   4453.0  Wii Sports Resort is a collection of fun sport...
4           NaT      NaN                                                NaN

               title  user_score platform_normalized manufacturer  avg_score
0         Wii Sports        81.0                 Wii     Nintendo       78.5
1                NaN         NaN                 NaN     Nintendo        NaN
2     Mario Kart Wii        85.0                 Wii     Nintendo       83.5
3  Wii Sports Resort        83.0                 Wii     Nintendo       81.5
4                NaN         NaN                 NaN     Nintendo        NaN

[5 rows x 23 columns]

In [121]:
print("NaN-värden efter sammanslagning:")
print(merged_games[["Name", "Platform", "manufacturer", "metascore", "user_score"]].isna().sum())

NaN-värden efter sammanslagning:
Name                0
Platform            0
manufacturer        0
metascore        9775
user_score      10197
dtype: int64

In [ ]:
manufacturer_map.update({"Wii U": "Nintendo", "GC": "Nintendo", "3DS": "Nintendo"})
merged_games["manufacturer"] = merged_games["Platform"].map(manufacturer_map)

print(merged_games)

In [ ]:
sony_games = merged_games[merged_games["manufacturer"] == "Sony"]
ms_games = merged_games[merged_games["manufacturer"] == "Microsoft"]
print("Sony spel med metascore:", sony_games["metascore"].notna().sum())
print("Microsoft spel med metascore:", ms_games["metascore"].notna().sum())

#Graphs diagrams

In [122]:
# Filter for Others and try a scatterplot
filtered_games = merged_games[merged_games["manufacturer"] == "Others"]
if filtered_games["metascore"].notna().sum() == 0:
    print("No score data available for Others.")
else:
    fig_scores = px.scatter(filtered_games, x="metascore", y="user_score", hover_data=["Name"], 
                            title="Metascore vs User Score (0-100)")
    fig_scores.show()

# Top 15 games by avg_score
top_15_scores = filtered_games[filtered_games["avg_score"].notna()].nlargest(15, "avg_score")
fig_top_scores = px.bar(top_15_scores, x="Name", y="avg_score", title="Top 15 Games (Average Score 0-100)")
fig_top_scores.show()

# Bottom 15 games by avg_score
bottom_15_scores = filtered_games[filtered_games["avg_score"].notna()].nsmallest(15, "avg_score")
fig_bottom_scores = px.bar(bottom_15_scores, x="Name", y="avg_score", title="Bottom 15 Games (Average Score 0-100)")
fig_bottom_scores.show()

# Shared page visualizations (all consoles)
# Top games (treemap)
top_games_all = merged_games.nlargest(10, "Global_Sales")
fig_top_games_all = px.treemap(top_games_all, path=["manufacturer", "Name"], values="Global_Sales",
                               title="Top 10 Games by Sales (All Consoles)")
fig_top_games_all.show()

# Console sales (pie chart)
console_sales_by_company = Consoles_sales.groupby("Company")["Units sold (million)"].sum().reset_index()
fig_console_sales_all = px.pie(console_sales_by_company, names="Company", values="Units sold (million)",
                               title="Console Sales by Company (All Consoles)")
fig_console_sales_all.show()

# Scores (box plot)
fig_scores_all = px.box(merged_games[merged_games["avg_score"].notna()], x="manufacturer", y="avg_score",
                        title="Score Distribution by Manufacturer (All Consoles)")
fig_scores_all.show()

In [124]:
sales_by_manufacturer = merged_games.groupby("manufacturer")["Global_Sales"].sum().reset_index()
fig = px.bar(sales_by_manufacturer, x="manufacturer", y="Global_Sales", 
             title="Total spelförsäljning per tillverkare")
fig.show()

In [123]:
games_no_score = merged_games[merged_games["Global_Sales"].notna() & merged_games["avg_score"].isna()]
#st.write("Spel med försäljning men ingen score:", games_no_score[["Name", "Platform", "Global_Sales"]])
print(games_no_score [["Name", "Platform", "Global_Sales"]].head(50))

                                             Name Platform  Global_Sales
1                               Super Mario Bros.      NES         40.24
4                        Pokemon Red/Pokemon Blue       GB         31.37
5                                          Tetris       GB         30.26
9                                       Duck Hunt      NES         28.31
10                                     Nintendogs       DS         24.76
12                    Pokemon Gold/Pokemon Silver       GB         23.10
18                              Super Mario World     SNES         20.61
19   Brain Age: Train Your Brain in Minutes a Day       DS         20.22
20                  Pokemon Diamond/Pokemon Pearl       DS         18.36
21                               Super Mario Land       GB         18.14
22                            Super Mario Bros. 3      NES         17.28
25                  Pokemon Ruby/Pokemon Sapphire      GBA         15.85
26                    Pokemon Black/Pokemon White       DS         15.32
30        Pokémon Yellow: Special Pikachu Edition       GB         14.64
32                            Pokemon X/Pokemon Y      3DS         14.35
33                      Call of Duty: Black Ops 3      PS4         14.24
45           Pokemon HeartGold/Pokemon SoulSilver       DS         11.90
49      Pokemon Omega Ruby/Pokemon Alpha Sapphire      3DS         11.33
50             Super Mario Land 2: 6 Golden Coins       GB         11.18
57                          Super Mario All-Stars     SNES         10.55
58              Pokemon FireRed/Pokemon LeafGreen      GBA         10.49
59                                 Super Mario 64       DS         10.42
71                            Donkey Kong Country     SNES          9.30
72                                      Minecraft     X360          9.20
76                               Super Mario Kart     SNES          8.76
81                Pokemon Black 2/Pokemon White 2       DS          8.33
88                       Pokémon Platinum Version       DS          7.84
89                                        Pac-Man     2600          7.81
92                   Star Wars Battlefront (2015)      PS4          7.67
95         Crash Bandicoot 2: Cortex Strikes Back       PS          7.58
96                            Super Mario Bros. 2      NES          7.46
97            Super Smash Bros. for Wii U and 3DS      3DS          7.45
101                     Call of Duty: Black Ops 3     XOne          7.30
114                     Medal of Honor: Frontline      PS2          6.83
116                               Crash Bandicoot       PS          6.82
117                                 Zumba Fitness      Wii          6.81
121                                       FIFA 12      PS3          6.69
127                           The Legend of Zelda      NES          6.51
130                       Pokémon Emerald Version      GBA          6.41
132                       Pokémon Crystal Version       GB          6.39
136          Street Fighter II: The World Warrior     SNES          6.30
143                          Sonic the Hedgehog 2      GEN          6.03
155                                        Tetris      NES          5.58
163                     Mario Kart: Super Circuit      GBA          5.47
164                             Super Mario World      GBA          5.46
165                               Pokemon Stadium      N64          5.45
168                                     Minecraft      PS3          5.42
170                                     Dr. Mario       GB          5.34
171                               Pokemon Pinball       GB          5.31
178                                Tomb Raider II       PS          5.24